/** Stream furniture driven from the control page: countdown, like goal, sponsor card and outro. */

export type Supporter = {
  name: string;
  kind: 'super' | 'member' | 'gift';
  /** Formatted Super Chat amount, or the number of gifted memberships. */
  detail?: string;
};

export type StreamStats = {
  messages: number;
  chatters: number;
  likes: number | null;
  supporters: Supporter[];
};

export type ShowState = {
  /** Server clock when this snapshot was sent, so overlays can correct for drift. */
  serverNow: number;
  countdown: {
    /** Epoch ms the countdown reaches zero; null when no countdown is running. */
    endsAt: number | null;
    /** Total length of the current countdown, adjusted when it is shifted. Drives the progress arc. */
    durationMs: number;
    title: string;
    topic: string;
  };
  likes: {
    count: number | null;
    /** The goal moves up by this many likes each time it is reached. */
    step: number;
  };
  /** Concurrent viewers of the connected stream; null when no stream is connected. */
  viewers: number | null;
  sponsor: {
    name: string;
    url: string;
    caption: string;
    /** SVG markup of the QR code for `url`, generated by the server. */
    qr: string | null;
    logoVersion: number | null;
    /** When on, overlays open the QR code for `showSeconds` out of every `everySeconds`, aligned to the clock. */
    auto: boolean;
    everySeconds: number;
    showSeconds: number;
    /** Set by "Show QR now": the QR code stays open until then whatever the cycle says. */
    visibleUntil: number | null;
  };
  /** The track OBS is playing, published by scripts/now-playing.py; null when nothing is playing. */
  music: {
    title: string;
    artist: string;
    /** Cache key for /show/music/cover; null when the track has no embedded cover. */
    coverVersion: number | null;
    /** When this track started, as seen by the watcher. */
    since: number;
  } | null;
  outro: {
    startedAt: number | null;
    stats: StreamStats | null;
  };
};
